version: '3.8'

services:
  registry:
    image: registry:3
    container_name: docker-registry
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      # Authentication
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
      
      # Storage configuration
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
      REGISTRY_STORAGE_DELETE_ENABLED: "true"
      
      # HTTP configuration
      REGISTRY_HTTP_ADDR: 0.0.0.0:5000
      REGISTRY_HTTP_HEADERS_X-Content-Type-Options: "[nosniff]"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Origin: "['http://localhost:8080']"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Methods: "['HEAD', 'GET', 'OPTIONS', 'DELETE']"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Headers: "['Authorization', 'Accept', 'Cache-Control']"
      REGISTRY_HTTP_HEADERS_Access-Control-Allow-Credentials: "[true]"
      REGISTRY_HTTP_HEADERS_Access-Control-Expose-Headers: "['Docker-Content-Digest']"
      
      # Logging
      REGISTRY_LOG_LEVEL: info
      REGISTRY_LOG_FORMATTER: text
      REGISTRY_LOG_FIELDS_SERVICE: registry
      
      # Health check
      REGISTRY_HEALTH_STORAGEDRIVER_ENABLED: "true"
      REGISTRY_HEALTH_STORAGEDRIVER_INTERVAL: 10s
      REGISTRY_HEALTH_STORAGEDRIVER_THRESHOLD: 3
    volumes:
      - ./data:/var/lib/registry
      - ./auth:/auth:ro
      - ./config/config.yml:/etc/docker/registry/config.yml:ro
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5000/v2/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - registry-network

  registry-ui:
    image: joxit/docker-registry-ui:latest
    container_name: registry-ui
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      - REGISTRY_TITLE=My Docker Registry
      - NGINX_PROXY_PASS_URL=http://registry:5000
      - PULL_URL=registry-ui.builtbychristiaan.com
      - DELETE_IMAGES=true
      - SHOW_CONTENT_DIGEST=true
      - SINGLE_REGISTRY=true
    depends_on:
      - registry
    networks:
      - registry-network

networks:
  registry-network:
    driver: bridge
